14ый спринт
CheburatorT1000/java-shareit pull request #2
Opened 2023-01-20 14:35 UTC by CheburatorT1000

2023-01-20 20:46 UTC, alexache requested changes

2023-01-20 20:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    int id;
Не хватает модификатора доступа у полей

2023-01-20 20:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoMapper.java
> +    public ItemDto toItemDto(Item item) {
Почему бы не сделать эти методы статическими? Чтобы и не создавать объекты класса Mapper

2023-01-20 20:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +                    .filter(item -> item.getName().toLowerCase().contains(text.toLowerCase())
text.toLowerCase можно было вынести до цикла, чтобы не повторять действие

2023-01-20 20:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        return items.values().stream()
(опционально) хорошо бы сделать вторую мапу для хранения вещей по юзерам, чтобы не делать полный проход по списку

2023-01-20 20:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    long owner;
лучше хранить обхект класса User

2023-01-20 20:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +            throw new NotFoundException("Инструмент с таким id отсутствует!");
в общем случае checkItemIdExists и getById можно объединить в один вызов getById, и, проверяя результат, можно получать ответ

2023-01-20 20:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +/**
Эти комментарии лучше или подчистить или наполнить осмысленным описанием (что не требуется по ТЗ)

2023-01-20 20:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +            return users.values().stream()
(опционально) Полное сканирование списка не самый лучший вариант, можно завести дополнительный сет для хранения существующих имейлов

2023-01-20 20:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +        if (userRepository.checkExistEmail(userDto.getEmail()))
Что если обновлять пользователя, но не менять у него имейл?

2023-01-20 20:46 UTC, alexache commented on src/main/java/ru/practicum/shareit/utils/ErrorResponse.java
> +    String error;
Отстутствует модификатор доступа

2023-01-21 16:18 UTC, CheburatorT1000 commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +        if (userRepository.checkExistEmail(userDto.getEmail()))
Тесты  постмана хотят измененный email

2023-01-27 14:00 UTC, merged