Add bookings
CheburatorT1000/java-shareit pull request #3
Opened 2023-02-05 20:09 UTC by CheburatorT1000

2023-02-06 22:11 UTC, alexache requested changes

2023-02-06 22:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
@Data включает в себя  @EqualsAndHashcode, которые несовместимы с JPA моделями, методы ты написал свои, но тогда зачем @Data? Можно и @Getter, @Setter обойтись

2023-02-06 22:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "ALL":
(опционально) Обычно под такие перечисления заводят свои Enum

2023-02-06 22:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        if (commentDto.getText() != null && commentDto.getText().isBlank())
Отчего не валидации на классе?

2023-02-06 22:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private Long request;
Пока еше лишнее поле, оно будет немного другим в будущем

2023-02-06 22:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public List<ItemDtoResponse> getAll(long ownerId) {
Очень все аккуратно и грамотно написано!

2023-02-06 22:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private ItemDtoResponse addBookingsAndComments(Item item, List<Booking> bookings, List<Comment> comments) {
(опционально) можно бы метод и статическим сделать, чтобы обозначить его независимость от стейтов

2023-02-07 05:46 UTC, CheburatorT1000 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        if (commentDto.getText() != null && commentDto.getText().isBlank())
согласен, глупо вышло

2023-02-07 05:46 UTC, CheburatorT1000 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "ALL":
исправил

2023-02-07 05:47 UTC, CheburatorT1000 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
понял, исправлено

2023-02-07 07:40 UTC, CheburatorT1000 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private Long request;
удалил

2023-02-07 07:41 UTC, CheburatorT1000 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public List<ItemDtoResponse> getAll(long ownerId) {
я старался! =)

2023-02-07 19:59 UTC, alexache approved these changes

2023-02-07 19:59 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/enums/BookingStatus.java
> +    CANCELED,
Лучше не объединять эти 2 перечисления в один. Да, они чем-то перекликаются, но не все значения идентичны

2023-02-08 04:57 UTC, merged