final
CheburatorT1000/java-shareit pull request #6
Opened 2023-03-01 23:40 UTC by CheburatorT1000

2023-03-02 22:08 UTC, alexache requested changes

2023-03-02 22:08 UTC, alexache commented on gateway/pom.xml
> +        <dependency>
Лучше тестовые зависимости писать после не-тестовых

2023-03-02 22:08 UTC, alexache commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
Валидаций не должно оставаться в модуле сервера

2023-03-02 22:08 UTC, alexache commented on server/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            throw new ValidationException("Unknown state: " + state);
Эта проверка теперь в модуле гейтвея, нет? Зачем она и здесь

2023-03-02 22:08 UTC, alexache commented on server/src/main/java/ru/practicum/shareit/utils/PageableMaker.java
> +            throw new ValidationException("Неправильно указанны параметры для просмотра!");
Эта проверка уже должна быть в гейтвее

2023-03-02 22:08 UTC, alexache commented on server/src/test/java/ru/practicum/shareit/item/service/ItemServiceImplIntTest.java
> +/*
Для чего этот закомментированный класс?

2023-03-03 04:24 UTC, CheburatorT1000 commented on gateway/pom.xml
> +        <dependency>
принял

2023-03-03 04:26 UTC, CheburatorT1000 commented on server/src/test/java/ru/practicum/shareit/item/service/ItemServiceImplIntTest.java
> +/*
остатки экспериментов в 3 часа ночи)

2023-03-03 04:26 UTC, CheburatorT1000 commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
принято

2023-03-03 18:55 UTC, alexache approved these changes

2023-03-03 19:12 UTC, merged